[package]
name = "from"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "fallible conversion"
license = "MIT OR Apache-2.0"

[dependencies]
void = { version = "1", default-features = false }
